name: taski

# Перечень volume
volumes:
  pg_data:
  static:

# Перечень контейнеров
services:
  # Имя и описание первого контейнера; имя выбирает разработчик.

  # Это контейнер БД
  postgres_db:
    # Из какого образа запустить контейнер:
    image: postgres:13.10
    # Файл (или список файлов) с переменными окружения
    env_file: .env
    # Какой volume подключить для этого контейнера
    volumes:
      - pg_data:/var/lib/postgresql/data
  # Имя и описание контейнера с бэкендом
  backend:
    # Из какого Dockerfile собирать образ для этого контейнера:
    build: ./backend/
    volumes:
      - static:/backend_static
    env_file: .env
    command: ./backend/start.sh
    # Какие контейнеры нужно запустить до старта этого контейнера:
    depends_on:
      - postgres_db
  # Имя третьего контейнера. Это контейнер с фронтендом
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  # Контейнер с Веб сервером
  web:
    build: ./gateway/
    ports:
      - "8080:80"
      - "8000:80"
    environment:
      - NGINX_PORT=80
    volumes:
      - static:/staticfiles
