name: Main Taski Workflow

on:
  push:
    branches:
      - main

jobs:
  checkout-and-print-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
  tests:
    needs: checkout-and-print-tree
    runs-on: ubuntu-latest
    # Блок services аналогичен docker-compose.yml
    services:
      postgres_db:
        image: postgres:13.10
        env:
          POSTGRES_USER: django_user
          POSTGRES_PASSWORD: django_password
          POSTGRES_DB: django_db
        ports:
          - 5432:5432
        # Эта конструкция описывает проверку готовности сервиса postgres
        # Если её не будет, то тесты могут запуститься раньше, чем сервер PostgreSQL
        # В результате тесты опять решат, что базы нет, — и упадут
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        # В action setup-python@v4 передаём параметр — версию Python
        with:
          python-version: "3.12"
      # Обновляем pip, устанавливаем flake8 и flake8-isort,
      # устанавливаем зависимости проекта
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install flake8==7.3.0 flake8-isort==7.0.0
          pip install -r ./backend/requirements.txt
      # Проверяем код с помощью flake8
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          python -m flake8 backend/ --count --show-source --statistics
      - name : Test with django test
        env:
          POSTGRES_USER: django_user
          POSTGRES_PASSWORD: django_password
          POSTGRES_DB: django_db
          DB_HOST: localhost
          DB_PORT: 5432
        run: |
          cd backend/
          python manage.py test
